repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v3.4.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.12.0'
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/pycqa/isort
    rev: '5.8.0'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '20.8b1'
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.0'
    hooks:
      - id: flake8
        args:
        - --max-line-length=100
